workflows:
  android-java-windows:
    name: Build APK on Windows
    max_build_duration: 30
    instance_type: windows_x2
    environment:
      vars:
        JAVA_HOME: "C:\\Program Files\\OpenJDK\\jdk-17"
    scripts:
      - name: Print Java version
        script: |
          echo %JAVA_HOME%
          "%JAVA_HOME%\\bin\\java.exe" -version
      - name: Clean project
        script: .\\gradlew clean
      - name: Build debug APK
        script: .\\gradlew assembleDebug
    artifacts:
      - app\\build\\outputs\\apk\\debug\\app-debug.apk
    publishing:
      email:
        recipients:
          - rinshadmorayur09@gmail.com
        notify:
          success: true
          failure: true
