workflows:
  android-java-windows:
    name: Build APK on Windows machine
    max_build_duration: 30
    instance_type: windows_x2  # Use the powerful Windows VM
    environment:
      os: windows
      vars:
        JAVA_HOME: C:\Program Files\OpenJDK\jdk-17
      paths:
        - C:\Program Files\Android\Android Studio\bin
        - C:\Users\builder\programs\android-sdk\platform-tools
    scripts:
      - name: Use correct Java version
        script: |
          echo JAVA_HOME=%JAVA_HOME%
      - name: Clean the project
        script: .\gradlew clean
      - name: Build debug APK
        script: .\gradlew assembleDebug
    artifacts:
      - app\build\outputs\apk\debug\app-debug.apk
    publishing:
      email:
        recipients:
          - rinshadmorayur09@gmail.com
        notify:
          success: true
          failure: true
