name: Android Release

on:
  push:
    branches:
      - main  # or your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'
        
    - name: Build with Gradle
      run: ./gradlew build

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Upload Release APK
      uses: actions/upload-artifact@v2
      with:
        name: release-apk
        path: app/build/outputs/apk/release/*.apk
