name: Android Release

on:
  push:
    branches:
      - main  # or your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Grant execution permissions to Gradle wrapper
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Upload Release APK
      uses: actions/upload-artifact@v2
      
    - name: Releasing using Hub
      uses: r0user/release-apk@main
      env:
       GITHUB_TOKEN: ${{ secrets.TOKEN }}
       APP_FOLDER: app
      with:
        name: release-apk
        path: app/build/outputs/apk/release/*.apk
